### ISSUE TITLE
Depth first search hangs

### ISSUE THREAD

**Issue by kpmoran** [tanzirul/a3e#2]
Depth first search hangs at the following step:

```
shell$ adb shell am startservice -n umd.troyd/.Ignite -e AUT <app and activity name>
```

I am on Mac OSX with the latest version of ruby, ruby gems, and nokogiri installed.

**Comment by gmendezm** [comment]
I fixed with the @shauvik 's tip but still hangs,

**Comment by andrirad** [comment]
Hi,

Did you all manage to fix this problem? I also tried the fix but the script keeps hanging. Below is a preview of what I have in logcat

D/dalvikvm(12420): GC_CONCURRENT freed 302K, 33% free 640K/944K, paused 0ms+0ms, total 2ms
I/ActivityManager(  788): Start proc a3e.process for service umd.troyd/.Ignite: pid=12438 uid=10065 gids={50065, 3003, 1028, 1015}
I/dalvikvm(12438): Enabling JNI app bug workarounds for target SDK version 10...
I/ActivityManager(  788): Force stopping com.ninegriddiary_beta appid=10065 user=0: start instr

**Comment by gowtham1984** [comment]
I have similar issue and logcat says. 

10-06 16:07:36.977 21954 21954 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: Application context cannot be null.
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-06 16:07:36.977 21954 21954 E AndroidRuntime: Caused by: java.lang.NullPointerException: Application context cannot be null.
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.android.gms.common.internal.zzab.zzb(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.firebase.FirebaseApp.zzek(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
10-06 16:07:36.977 21954 21954 E AndroidRuntime:    ... 10 more

After search, looks like Google Play version needed to be added in the AndroidManifest.xml which I tried putting it troyd/AndroidManifest.xml file by adding the following entry 
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
and also create integers.xml defining google_play_services_version. 

But, still the same error, can you please help me.

**Comment by tanzirul** [comment]
## Hi, can you first check whether you can install and uninstall the app through adb command?

Tanzirul Azim

**Comment by gowtham1984** [comment]
Yes, was able to install & uninstall an app using adb command. Can you tell me what needs to be done to get it working. Thanks

**Comment by gowtham1984** [comment]
and I see an error message on the mobile/emulator saying Unfortunately the process a3e.process has stopped with the above exception in adb logcat

**Comment by gowtham1984** [comment]
@tanzirul any help please ?
